{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" action="nav.php?act=add" onsubmit="return add_section()">
            <div class="form-group">
                <label class="control-label col-md-2">栏目名称</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="name" id="name" placeholder="请填写栏目名称"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">上级栏目</label>
                <div class="col-md-4">
                    <select class="form-control" name="parent_id" id="parent_id">
                        <option value="0">顶级栏目</option>
                        {if $section_list}
                        {foreach $section_list as $_section}
                        <option value="{$_section.id}">{$_section.name}</option>
                        {/foreach}
                        {/if}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">封面</label>
                <div class="col-md-4">
                    <img class="img-thumbnail" id="cover-preview" width="480" height="320" src="no_image.php?w=480&h=320"/>
                    <input type="hidden" name="cover" id="cover"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">缩略图</label>
                <div class="col-md-4">
                    <img class="img-thumbnail" id="thumb-preview" width="100" height="100" src="no_image.php?w=100&h=100"/>
                    <input type="hidden" name="thumb" id="thumb"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">排序</label>
                <div class="col-md-4">
                    <input type="number" class="form-control" name="sort" id="sort" placeholder="请填写排序" value="50"/>
                    <div class="help-block">请填写正整数，数字越小，排序越前</div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">&nbsp;</label>
                <div class="col-md-10">
                    <button class="btn btn-primary" name="submit" id="submit">新增</button>
                    <a class="btn btn-default" href="section.php?act=list">返回</a>
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>
<link rel="stylesheet" href="../plugins/common/kindeditor/themes/default/default.css" />
<script src="../plugins/common/kindeditor/kindeditor.js"></script>
<script src="../plugins/common/kindeditor/lang/zh_CN.js"></script>
<script type="text/javascript">
    KindEditor.ready(function(K) {
        var editor = K.editor({
            allowFileManager : true
        });
        K('#cover-preview').click(function() {
            editor.loadPlugin('insertimage', function() {
                editor.plugin.imageDialog({
                    imageUrl : K('#cover').val(),
                    clickFn : function(url) {
                        K('#cover').val(url);
                        K('#cover-preview').attr('src', url);
                        editor.hideDialog();
                    }
                });
            });
        });
        K('#thumb-preview').click(function() {
            editor.loadPlugin('insertimage', function() {
                editor.plugin.imageDialog({
                    imageUrl : K('#thumb').val(),
                    clickFn : function(url) {
                        K('#thumb').val(url);
                        K('#thumb-preview').attr('src', url);
                        editor.hideDialog();
                    }
                });
            });
        });
    });

    function add_section() {
        var data = {
            name: $.trim($('#name').val()),
            parent_id: parseInt($('#parent_id').val()),
            cover: $.trim($('#cover').val()),
            thumb: $.trim($('#thumb').val()),
            sort: parseInt($('#sort').val()),
            opera: 'add'
        };

        var error_msg = '';

        if(data.name == '') {
            error_msg += '-请填写栏目名称<br/>';
            $('#name').parent().addClass('has-error');
        } else {
            $('#name').parent().removeClass('has-error');
        }

        if(isNaN(data.parent_id) || data.parent_id < 0) {
            error_msg += '-请选择上级栏目<br/>';
            $('#parent_id').parent().addClass('has-error');
        } else {
            $('#parent_id').parent().removeClass('has-error');
        }

        if(data.cover == '') {
            error_msg += '-请选择栏目封面<br/>';
            $('#cover').parent().addClass('has-error');
        } else {
            $('#cover').parent().removeClass('has-error');
        }

        if(data.thumb == '') {
            error_msg += '-请选择缩略图<br/>';
            $('#thumb').parent().addClass('has-error');
        } else {
            $('#thumb').parent().removeClass('has-error');
        }

        if(isNaN(data.sort) || data.sort < 0) {
            error_msg += '-请填写排序<br/>';
            $('#sort').parent().addClass('has-error');
        } else {
            $('#sort').parent().removeClass('has-error');
        }

        if(error_msg == '') {
            var url = 'section.php';

            $.post(url, data, add_section_success, 'json');
        } else {
            layer.alert(error_msg);
        }

        return false;
    }

    function add_section_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                btn: ['继续添加', '查看列表'],
                yes: function(index, layero) {
                    layer.close(index);
                    window.location.reload();
                },
                cancel: function() {
                    window.location.href = 'section.php?act=list';
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}