{extends file='index.phtml'}
{block name='content'}
<section class="sf-block">
    <h2 class="sf-block-title">
        品牌中心
    </h2>

    <div class="sf-block-content-style-3 {if !$brand_list}empty{/if}">
        {if $brand_list}
        {foreach $brand_list as $brand}
        <div class="sf-product-item">
            <a href="brand.php?id={$brand.id}">
                <img src="{$brand.logo}" alt="{$brand.name|escape}" class="sf-product-image"/>
                <p>{$brand.name|escape}</p>
                <p class="sf-product-desc">{$brand.desc|escape}</p>
            </a>
        </div>
        {if $brand@iteration mod 3 eq 0}
        <div class="clearfix"></div>
        {/if}
        {/foreach}
        {else}
        没有产品了
        {/if}
    </div>
</section>
{/block}

{block name="script"}
<script type="text/javascript">
    $(function () {

    });
</script>
{/block}