{extends file='index.phtml'}
{block name='content'}
<section class="sf-block">
    <h2 class="sf-block-title">
        {$category.name|escape}
    </h2>

    <div class="sf-block-content-style-3 {if !$product_list}empty{/if}">
        {if $product_list}
        {foreach $product_list as $product}
        <div class="sf-product-item">
            <a href="product.php?id={$product.id}">
                <img src="{$product.thumb}" alt="{$product.name|escape}" class="sf-product-image"/>
                <p>{$product.name|escape}</p>
                <p class="sf-product-price">{sprintf('￥%.2f', $product.price)}</p>
            </a>
        </div>
        {if $product@iteration mod 3 eq 0}
        <div class="clearfix"></div>
        {/if}
        {/foreach}
        {else}
        没有产品了
        {/if}
    </div>
</section>
{/block}

{block name="script"}
<script type="text/javascript">
    $(function () {

    });
</script>
{/block}