{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" action="article.php?act=add" onsubmit="return edit_article()">
            <div class="form-group">
                <label class="control-label col-md-2">资讯标题</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="title" id="title" placeholder="请填写资讯标题" value="{$article.title}"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">所属栏目</label>
                <div class="col-md-4">
                    <select class="form-control" name="section_id" id="section_id">
                        {if $section_list}
                        {foreach $section_list as $_section}
                        <option value="{$_section.id}" {if $article.section_id eq $_section.id}selected="selected"{/if}>{$_section.name}</option>
                        {/foreach}
                        {/if}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">作者</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="author" id="author" placeholder="请填写作者" value="{$article.author}"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">简介</label>
                <div class="col-md-4">
                    <textarea class="form-control" name="desc" id="desc" placeholder="请填写简介">{$article.desc}</textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">关键词</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="keywords" id="keywords" placeholder="请填写关键词" value="{$article.keywords}"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">封面</label>
                <div class="col-md-4">
                    <img class="img-thumbnail" id="cover-preview" width="480" height="320" src="{$article.cover}"/>
                    <input type="hidden" name="cover" id="cover" value="{$article.cover}"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">缩略图</label>
                <div class="col-md-4">
                    <img class="img-thumbnail" id="thumb-preview" width="100" height="100" src="{$article.thumb}"/>
                    <input type="hidden" name="thumb" id="thumb" value="{$article.thumb}"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">资讯内容</label>
                <div class="col-md-4">
                    <textarea name="content" id="content">{$article.content}</textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">排序</label>
                <div class="col-md-4">
                    <input type="number" class="form-control" name="sort" id="sort" placeholder="请填写排序" value="{$article.sort}"/>
                    <div class="help-block">请填写正整数，数字越小，排序越前</div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">状态</label>
                <div class="col-md-4">
                    <select class="form-control" name="status" id="status">
                        <option value="1">发布</option>
                        <option value="0" {if $article.status eq 0}selected="selected"{/if}>存草稿</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">&nbsp;</label>
                <div class="col-md-10">
                    <button class="btn btn-primary" name="submit" id="submit">修改</button>
                    <a class="btn btn-default" href="article.php?act=list">返回</a>
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>
<link rel="stylesheet" href="../plugins/common/kindeditor/themes/default/default.css" />
<script src="../plugins/common/kindeditor/kindeditor.js"></script>
<script src="../plugins/common/kindeditor/lang/zh_CN.js"></script>
<link rel="stylesheet" href="../plugins/common/kindeditor/plugins/code/prettify.css" />
<script charset="utf-8" src="../plugins/common/kindeditor/plugins/code/prettify.js"></script>

<script type="text/javascript">
    var content = null;

    KindEditor.ready(function(K) {
        var editor = K.editor({
            allowFileManager : true
        });
        K('#cover-preview').click(function() {
            editor.loadPlugin('insertimage', function() {
                editor.plugin.imageDialog({
                    imageUrl : K('#cover').val(),
                    clickFn : function(url) {
                        K('#cover').val(url);
                        K('#cover-preview').attr('src', url);
                        editor.hideDialog();
                    }
                });
            });
        });
        K('#thumb-preview').click(function() {
            editor.loadPlugin('insertimage', function() {
                editor.plugin.imageDialog({
                    imageUrl : K('#thumb').val(),
                    clickFn : function(url) {
                        K('#thumb').val(url);
                        K('#thumb-preview').attr('src', url);
                        editor.hideDialog();
                    }
                });
            });
        });
        content = K.create('textarea[name="content"]', {
            allowFileManager : true,
            width: 670,
            height: 300,
            afterCreate : function() {
                var self = this;
                K.ctrl(document, 13, function() {
                    self.sync();
                    K('form')[0].submit();
                });
                K.ctrl(self.edit.doc, 13, function() {
                    self.sync();
                    K('form')[0].submit();
                });
            }
        });
        prettyPrint();
    });

    function edit_article() {
        content.sync();
        var data = {
            title: $.trim($('#title').val()),
            section_id: parseInt($('#section_id').val()),
            author: $.trim($('#author').val()),
            desc: $.trim($('#desc').val()),
            keywords: $.trim($('#keywords').val()),
            cover: $.trim($('#cover').val()),
            thumb: $.trim($('#thumb').val()),
            content: $('#content').val(),
            sort: parseInt($('#sort').val()),
            status: parseInt($('#status').val()),
            opera: 'edit',
            id: {$article.id}
        };

        var error_msg = '';

        if(data.title == '') {
            error_msg += '-请填写栏目名称<br/>';
            $('#title').parent().addClass('has-error');
        } else {
            $('#title').parent().removeClass('has-error');
        }

        if(isNaN(data.section_id) || data.section_id < 0) {
            error_msg += '-请选择所属栏目<br/>';
            $('#section_id').parent().addClass('has-error');
        } else {
            $('#section_id').parent().removeClass('has-error');
        }

        if(data.author == '') {
            error_msg += '-请填写作者<br/>';
            $('#author').parent().addClass('has-error');
        } else {
            $('#author').parent().removeClass('has-error');
        }

        if(data.desc == '') {
            error_msg += '-请填写简介<br/>';
            $('#desc').parent().addClass('has-error');
        } else {
            $('#desc').parent().removeClass('has-error');
        }

        if(data.keywords == '') {
            error_msg += '-请填写关键词<br/>';
            $('#keywords').parent().addClass('has-error');
        } else {
            $('#keywords').parent().removeClass('has-error');
        }

        if(data.cover == '') {
            error_msg += '-请选择栏目封面<br/>';
            $('#cover').parent().addClass('has-error');
        } else {
            $('#cover').parent().removeClass('has-error');
        }

        if(data.thumb == '') {
            error_msg += '-请选择缩略图<br/>';
            $('#thumb').parent().addClass('has-error');
        } else {
            $('#thumb').parent().removeClass('has-error');
        }

        if(data.content == '') {
            error_msg += '-请填写资讯内容<br/>';
            $('#content').parent().addClass('has-error');
        } else {
            $('#content').parent().removeClass('has-error');
        }

        if(isNaN(data.sort) || data.sort < 0) {
            error_msg += '-请填写排序<br/>';
            $('#sort').parent().addClass('has-error');
        } else {
            $('#sort').parent().removeClass('has-error');
        }

        if(error_msg == '') {
            var url = 'article.php';

            $.post(url, data, edit_article_success, 'json');
        } else {
            layer.alert(error_msg);
        }

        return false;
    }

    function edit_article_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                btn: ['继续修改', '查看列表'],
                yes: function(index, layero) {
                    layer.close(index);
                    window.location.reload();
                },
                cancel: function() {
                    window.location.href = 'article.php?act=list';
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}