<div class="aslide col-md-2 col-sm-2">
    <div class="panel-group" role="tablist">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="menu-group">
                <h4 class="panel-title">
                    <a href="index.php">首页</a>
                </h4>
            </div>
            {foreach $menus as $menu}
            <div class="panel-heading" role="tab" id="menu-group-{$menu@key}">
                <h4 class="panel-title" data-target="#menu-list-{$menu@key}" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="menu-list-{$menu@key}">
                    {$menu.group}
                </h4>
            </div>
            <div class="panel-collapse collapse in" role="tabpanel" id="menu-list-{$menu@key}" aria-labelledby="menu-group-{$menu@key}" aria-expanded="true">
                <ul class="list-group">
                    {foreach $menu.sub_menus as $menu_item}
                    {if $menu_item.display}
                    <li class="list-group-item">
                        <a href="{$menu_item.url}">{$menu_item.title}</a>
                    </li>
                    {/if}
                    {/foreach}
                </ul>
            </div>
            {if $menu@last}
            <div class="panel-footer">
                <a href="logout.php">安全退出</a>
            </div>
            {/if}
            {/foreach}
        </div>
    </div>
</div>