<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <meta http-equiv="Cache-Control" content="no-cache"/>
    <title>Group Buy</title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="author" content="Winsen"/>
    <meta name="version" content="v.1.0.0"/>
    <link rel="shortcut icon" type="image/x-icon" href="{$theme_dir}/images/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="{$theme_dir}/css/reset.css"/>
    <link rel="stylesheet" type="text/css" href="{$theme_dir}/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="{$theme_dir}/css/bootstrap-theme.min.css"/>
    <link rel="stylesheet" type="text/css" href="{$theme_dir}/css/style.css"/>
    <script type="text/javascript" src="{$theme_dir}/js/jquery.js"></script>
    <script type="text/javascript" src="{$theme_dir}/js/layer.js"></script>
    <script type="text/javascript" src="{$theme_dir}/js/bootstrap.min.js"></script>
    <style>
        .login-form {
            display: block;
            margin: 100px auto 0;
            float: none;
        }
    </style>
</head>
<body>
<div class="col-md-4 login-form">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">{$_P['page']['title']}</div>
        </div>
        <div class="panel-body">
            <form method="post" action="login.php" onsubmit="return login();">
                <div class="form-group">
                    <label class="control-label sr-only">管理员账号</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-user"></span>
                        </div>
                        <input type="text" class="form-control" id="account" name="account" placeholder="请输入管理员账号"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label sr-only">管理员密码</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-lock"></span>
                        </div>
                        <input type="password" class="form-control" id="password" name="password" placeholder="请输入管理员密码"/>
                    </div>
                </div>

                {if $smarty.session.login_fail gt 3}
                <div class="form-group">
                    <label class="control-label sr-only">验证码</label>
                    <div class="input-group">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-check"></span>
                        </div>
                        <input type="text" class="form-control" id="code" name="code" placeholder="请输入验证码"/>
                        <div class="input-group-addon">
                            <img src="code.php"/>
                        </div>
                    </div>
                </div>
                {else}
                <input type="hidden" name="code" id="code" value="code"/>
                {/if}

                <div class="form-group text-right">
                    <button class="btn btn-primary fixed-center col-md-4">登 录</button>
                </div>
            </form>
        </div>
        <div class="panel-footer">
            {$_P['page']['copyright']}
        </div>
    </div>
</div>
<script type="text/javascript">
    function login() {
        var login_data = {
            account: $.trim($('#account').val()),
            password: $.trim($('#password').val()),
            code: $.trim($('#code').val()),
            opera: 'login'
        };

        var error_msg = '';

        if(login_data.account == '') {
            error_msg += '-请输入管理员账号<br/>';
            $('#account').parent().addClass('has-error');
        } else {
            $('#account').parent().removeClass('has-error');
        }
        
        if(login_data.password == '') {
            error_msg += '-请输入登录密码<br/>';
            $('#password').parent().addClass('has-error');
        } else {
            $('#password').parent().removeClass('has-error');
        }
        
        if(login_data.code == '') {
            error_msg += '-请输入验证码<br/>';
            $('#code').parent().addClass('has-error');
        } else {
            $('#code').parent().removeClass('has-error');
        }

        if(error_msg == '') {
            var url = 'login.php';

            $.post(url, login_data, login_success, 'json');
        } else {
            layer.alert(error_msg);
        }

        return false;
    }

    function login_success(response) {
        layer.alert(response.message, function(a) {
            if(response.error == 0) {
                window.location.href = 'index.php';
            } else {
                layer.close(a);

                if(response.login_fail > 3 && !$('#code').length) {
                    window.location.reload();
                }
            }
        });
    }
</script>
</body>
</html>