<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="{$config.meta_keywords|escape}">
    <meta name="description" content="{$config.meta_description|escape}">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{if isset($_P.page.title) and $_P.page.title neq ''}{$_P.page.title}-{/if}{$config.site_name|escape}</title>
    <link href="{$template_path}/css/style.min.css" type="text/css" rel="stylesheet"/>
</head>
<body>
    {block name="header"}
    <div class="header">
        <div class="header-content">
            <img class="jk-site-logo" src="{$config.logo}"/>
            <h1 class="jk-site-theme">{$config.site_theme|escape}</h1>
            <h2 class="jk-site-hot-line">招商热线: {$config.service_phone|escape}</h2>

            <div class="jk-top-nav-bar">
                {if isset($nav_list.top)}
                {foreach $nav_list.top as $_nav}
                <a href="{$_nav.url}" class="jk-top-nav-item">{$_nav.title|escape}</a>
                {/foreach}
                {/if}
            </div>

            <div class="jk-middle-nav-bar">
                {if isset($nav_list.middle)}
                {foreach $nav_list.middle as $_nav}
                <a href="{$_nav.url}" class="jk-middle-nav-item {if $_nav.active}active{/if}">{$_nav.title|escape}</a>
                {/foreach}
                {/if}
            </div>
        </div>
    </div>
    {/block}

    {block name="content"}
    <div class="jk-slider-wrapper">
        <div class="jk-slider">
            {foreach $ad_list as $ad}
            <a href="{$ad.url}">
                <img src="{$ad.img}" alt="{$ad.alt|escape}" width="{$ad.width}" height="{$ad.height}"/>
            </a>
            {/foreach}
        </div>

        <div class="jk-quick-menu">
            <h2 class="jk-block-title"><i></i>快捷功能</h2>
            <div class="jk-quick-menu-list">
                <a href="#" class="jk-quick-menu-item">
                    <img src="{$template_path}/images/icon_member.png" class="jk-quick-menu-icon"/>
                    <p>注册／登录</p>
                </a>
                <a href="#" class="jk-quick-menu-item">
                    <img src="{$template_path}/images/icon_category.png" class="jk-quick-menu-icon"/>
                    <p>产品分类</p>
                </a>
                <a href="#" class="jk-quick-menu-item">
                    <img src="{$template_path}/images/icon_service.png" class="jk-quick-menu-icon"/>
                    <p>在线咨询</p>
                </a>
                <a href="#" class="jk-quick-menu-item">
                    <img src="{$template_path}/images/icon_business.png" class="jk-quick-menu-icon"/>
                    <p>招商加盟</p>
                </a>
                <a href="#" class="jk-quick-menu-item">
                    <img src="{$template_path}/images/icon_order.png" class="jk-quick-menu-icon"/>
                    <p>订单查询</p>
                </a>
                <a href="#" class="jk-quick-menu-item">
                    <img src="{$template_path}/images/icon_scan.png" class="jk-quick-menu-icon"/>
                    <p>防伪查询</p>
                </a>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="jk-block-wrapper">
            <h2 class="jk-block-title">
                <i class="jk-block-title-icon"></i>
                健康就是这么简单
                <a href="#" class="jk-block-title-more">更多>></a>
            </h2>
            <div class="jk-article-list-1">
                {if $book_list}
                {foreach $book_list as $section}
                {if $section@first}
                <div class="jk-article-cover">
                    <img src="{$section.cover}"/>
                    <div class="js-article-title">
                        <span id="article-title">{$section.title|escape}</span>
                        <span class="jk-article-read">
                            <i class="jk-article-read-icon"></i>
                            {$section.view_count}
                        </span>
                    </div>
                </div>
                <div class="jk-article-list">
                {/if}
                    <dl {if $section@first}class="active"{/if}>
                        <dt data-cover="{$section.cover}" data-read="{$section.view_count}">
                            <span>{$section.title|escape}</span>
                            <i class="jk-article-active-icon"></i>
                        </dt>
                        <dd>
                            简述:
                            <p>
                                {$section.desc|escape|truncate:74:'...'}
                                <span>
                                    <a href="article.php?id={$section.id}">[ 阅读 ]</a>
                                </span>
                            </p>
                        </dd>
                    </dl>
                {if $section@last}
                </div>
                {/if}
                {/foreach}
                {/if}
            </div>
        </div>

        <div class="jk-block-wrapper">
            <h2 class="jk-block-title">
                <i class="jk-block-title-icon"></i>
                专家观点
                <a href="#" class="jk-block-title-more">更多>></a>
            </h2>
            <div class="jk-article-list-2">
            </div>
        </div>
    </div>
    {/block}

    {block name="common"}
    <div class="content">
        <div class="jk-block-wrapper">
            <h2 class="jk-block-title">
                <i class="jk-block-title-icon"></i>
                品牌视窗
                <a href="#" class="jk-block-title-more">更多>></a>
            </h2>
            <div class="jk-brand-list">
                {foreach $brand_list as $brand}
                <div class="jk-brand-list-item">
                    <img src="{$brand.logo}" alt="{$brand.name|escape}" class="jk-brand-list-item-logo"/>
                    <p class="jk-brand-list-item-name">{$brand.name|escape}</p>
                    <a href="brand.php?id={$brand.id}" class="jk-brand-list-item-link">查看产品</a>
                </div>
                {/foreach}
            </div>
        </div>
    </div>
    {/block}

    {block name="footer"}
    <div class="footer">
        <div class="footer-content">
            <img src="{$config.wechat_qrcode}" class="jk-footer-qrcode"/>
            <img src="{$config.taobao_qrcode}" class="jk-footer-qrcode"/>

            <div class="jk-footer-info">
                <div class="jk-bottom-nav-bar">
                    {if isset($nav_list.middle)}
                    {foreach $nav_list.middle as $_nav}
                    <a href="{$_nav.url}" class="jk-bottom-nav-item">{$_nav.title|escape}</a>
                    {/foreach}
                    {/if}
                </div>
                <div class="jk-footer-info-line">
                    <h3 class="jk-service-phone">客服热线: {$config.service_phone|escape}</h3>
                    <p>备案号: <a href="http://www.miibeian.gov.cn">{$config.case_number|escape}</a></p>
                </div>
                <div class="jk-footer-info-line">
                    <p class="jk-company-address">公司地址: {$config.company_address|escape}</p>
                    <p class="jk-copyright">Copyright &copy; {$config.copyright}. All Rights Reserved. 2015 ~ {date('Y')}</p>
                </div>
            </div>
        </div>
    </div>
    {/block}

    <script type="text/javascript" src="{$template_path}/js/jquery.min.js"></script>
    {block name="script"}
    <script type="text/javascript">
        $(function () {
            $('.jk-article-list dt').hover(function () {
                $('.jk-article-list dl').removeClass('active');
                var cover = $('.jk-article-cover>img');
                var view = $('.jk-article-cover .jk-article-read');
                var title = $('#article-title');

                var view_count = $(this).attr('data-read');
                view.html('<i class="jk-article-read-icon"></i>' + view_count);
                var title_str = $(this).find('span').text();
                title.text(title_str);
                cover.attr('src', $(this).attr('data-cover'));
                $(this).parent().addClass('active');
            });
        });
    </script>
    {/block}
</body>
</html>