{extends file='index.phtml'}
{block name="content"}

<div class="content">
    <div class="jk-left-container">
        {* 二级导航栏 *}
        <div class="jk-sub-nav">
            <h2 class="jk-sub-nav-header">
                <i class="jk-icon-info"></i>
                {$sub_nav.title|escape}
            </h2>
            <ul class="jk-sub-nav-list">
                {foreach $sub_nav.nav_list as $_nav}
                <li>
                    <a href="{$_nav.url}" class="jk-sub-nav-item {if $_nav.active}active{/if}">
                        <i></i>
                        {$_nav.title|escape}
                        <i></i>
                    </a>
                </li>
                {/foreach}
            </ul>
        </div>

        <div class="jk-left-qrcode">
            <img src="{$config.wechat_qrcode}"/>
            <p>扫描二维码，关注公众号</p>
        </div>
    </div>

    {* 主内容界面 *}
    <div class="jk-right-container">
        {* 工具栏 *}
        <div class="jk-tool-bar">
            <i class="jk-icon-info-white"></i>
            <ol class="jk-breadcrumb">
                {foreach $breadcrumb as $location}
                {if $location@last}
                <li class="active">{$location.name}</li>
                {else}
                <li><a href="{$location.url}">{$location.name}</a></li>
                {/if}
                {/foreach}
            </ol>

            <div class="jk-search-bar">
                <form method="get" action="search.php" name="search-form" id="search-form" onsubmit="return search_info();">
                    <select class="jk-search-select" name="type" id="type">
                        <option value="article">搜资讯</option>
                        <option value="product">搜产品</option>
                    </select>
                    <input type="text" class="jk-search-input" name="keyword" id="keyword" placeholder="请输入关键词"/>
                    <input type="submit" name="submit" value="搜索" id="search-submit" class="jk-search-btn"/>
                </form>
            </div>
        </div>

        <div class="jk-content-container">
            <div class="jk-product-info">
                <div class="jk-product-image">
                    <img src="{$product.image|escape}" alt="{$product.name|escape}"/>
                </div>
                <div class="jk-product-attr">
                    <h2 class="jk-product-name">{$product.name|escape}</h2>
                    <p class="jk-product-desc">{$product.desc|escape|truncate:20:'...'}</p>
                    <p class="jk-product-desc">商品品牌: {$product.brand_name|escape}</p>
                    <p class="jk-product-desc">建议零售价: <span class="jk-product-price">{$product.price}</span></p>
                    <div class="jk-product-button-group">
                        <a href="#apply" class="jk-btn-apply">申请代理</a>
                        <a href="#buy" class="jk-btn-buy">前往购买</a>
                    </div>
                </div>
            </div>
            <div class="jk-product-detail">
                <h2 class="jk-product-detail-title">
                    <i class="jk-icon-order"></i>
                    产品详情
                </h2>
                <div>
                    {$product.detail}
                </div>
            </div>
        </div>
    </div>
</div>
{/block}

{block name="script"}
<script type="text/javascript">
    $(function () {
    });

    function search_info() {
        var form = $('#search-form'),
            keyword,
            type;

        if(form.hasClass('active')) {
            keyword = $('#keyword').val();
            type = $('#type').val();

            if(keyword === '' || $.trim(keyword) === '') {
                alert('请输入要搜索的关键词');
                return false;
            }

            if(type === '') {
                alert('请选择要搜索的资讯类型');
                return false;
            }
            return true;
        }

        form.addClass('active');

        return false;
    }
</script>
{/block}