{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th width="30%">广告位置</th>
                    <th width="20%">宽度</th>
                    <th width="20%">高度</th>
                    <th width="30%">操作</th>
                </tr>
            </thead>
            <tbody>
            {if isset($ad_pos_list) and count($ad_pos_list)}
            {foreach $ad_pos_list as $ad_pos}
            <tr>
                <td>{$ad_pos.pos_name|escape}</td>
                <td>{$ad_pos.width|intval}</td>
                <td>{$ad_pos.height|intval}</td>
                <td>
                    <a href="ad_position.php?act=edit&id={$ad_pos.id}" class="btn btn-default" title="编辑">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>

                    <a href="javascript:void(0);" data-id="{$ad_pos.id}" class="btn btn-default delete" title="删除">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td colspan="4" class="text-center">
                    暂无广告位置，请先 <a href="ad_position.php?act=add">添加</a>
                </td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>
<script type="text/javascript">
    $(function(){
        var delete_btns = $('.delete');

        delete_btns.each(function(i, e) {
            $(this).bind('click', delete_ad_position);
        });
    });

    function delete_ad_position() {
        var data = {
            id: $(this).attr('data-id'),
            opera: 'delete'
        };

        var url = 'ad_position.php';

        layer.confirm('您确定要删除该广告位置?', { icon: 3 }, function() {
            $.post(url, data, delete_ad_position_success, 'json');
        });
    }

    function delete_ad_position_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                yes: function() {
                    window.location.reload();
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}