{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" action="nav.php?act=add" onsubmit="return add_category()">
            <div class="form-group">
                <label class="control-label col-md-2">分类名称</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="name" id="name" placeholder="请填写商品分类名称"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">上级分类</label>
                <div class="col-md-4">
                    <select class="form-control" name="parent_id" id="parent_id">
                        <option value="0">顶级分类</option>
                        {if $category_list}
                        {foreach $category_list as $_category}
                        <option value="{$_category.id}">{$_category.name}</option>
                        {/foreach}
                        {/if}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">排序</label>
                <div class="col-md-4">
                    <input type="number" class="form-control" name="sort" id="sort" placeholder="请填写排序" value="50"/>
                    <div class="help-block">请填写正整数，数字越小，排序越前</div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">&nbsp;</label>
                <div class="col-md-10">
                    <button class="btn btn-primary" name="submit" id="submit">新增</button>
                    <a class="btn btn-default" href="category.php?act=list">返回</a>
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>
<script type="text/javascript">
    function add_category() {
        var data = {
            name: $.trim($('#name').val()),
            parent_id: parseInt($('#parent_id').val()),
            sort: parseInt($('#sort').val()),
            opera: 'add'
        };

        var error_msg = '';

        if(data.name == '') {
            error_msg += '-请填写商品分类名称<br/>';
            $('#name').parent().addClass('has-error');
        } else {
            $('#name').parent().removeClass('has-error');
        }

        if(isNaN(data.parent_id) || data.parent_id < 0) {
            error_msg += '-请选择上级商品分类<br/>';
            $('#parent_id').parent().addClass('has-error');
        } else {
            $('#parent_id').parent().removeClass('has-error');
        }

        if(isNaN(data.sort) || data.sort < 0) {
            error_msg += '-请填写排序<br/>';
            $('#sort').parent().addClass('has-error');
        } else {
            $('#sort').parent().removeClass('has-error');
        }

        if(error_msg == '') {
            var url = 'category.php';

            $.post(url, data, add_category_success, 'json');
        } else {
            layer.alert(error_msg);
        }

        return false;
    }

    function add_category_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                btn: ['继续添加', '查看列表'],
                yes: function(index, layero) {
                    layer.close(index);
                    window.location.reload();
                },
                cancel: function() {
                    window.location.href = 'category.php?act=list';
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}