{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th>分类名称</th>
                    <th>链接</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
            {if isset($category_list) and count($category_list)}
            {foreach $category_list as $category}
            <tr>
                <td>{$category.name}</td>
                <td>http://{$smarty.server.SERVER_NAME}/category.php?id={$category.id}</td>
                <td>
                    <a href="category.php?act=edit&id={$category.id}" class="btn btn-default" title="编辑">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>

                    <a href="javascript:void(0);" data-id="{$category.id}" class="btn btn-default delete" title="删除">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td colspan="3" class="text-center">
                    暂无商品分类，请先 <a href="category.php?act=add">添加</a>
                </td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>
<script type="text/javascript">
    $(function(){
        var delete_btns = $('.delete');

        delete_btns.each(function(i, e) {
            $(this).bind('click', delete_category);
        });
    });

    function delete_category() {
        var data = {
            id: $(this).attr('data-id'),
            opera: 'delete'
        };

        var url = 'category.php';

        layer.confirm('您确定要删除该商品分类?', { icon: 3 }, function() {
            $.post(url, data, delete_category_success, 'json');
        });
    }

    function delete_category_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                yes: function() {
                    window.location.reload();
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}