{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" action="article.php?act=add" onsubmit="return add_product()">
            <div class="form-group">
                <label class="control-label col-md-2">商品标题</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="name" id="name" placeholder="请填写商品标题"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">所属分类</label>
                <div class="col-md-4">
                    <select class="form-control" name="category_id" id="category_id">
                        {if $category_list}
                        {foreach $category_list as $_category}
                        <option value="{$_category.id}">{$_category.name}</option>
                        {/foreach}
                        {/if}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">所属品牌</label>
                <div class="col-md-4">
                    <select class="form-control" name="brand_id" id="brand_id">
                        <option value="0">请选择品牌</option>
                        {if $brand_list}
                        {foreach $brand_list as $_brand}
                        <option value="{$_brand.id}">{$_brand.name}</option>
                        {/foreach}
                        {/if}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">单位</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="unit" id="unit" placeholder="请填写单位"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">市场价</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="market_price" id="market_price" placeholder="请填写市场价"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">零售价</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="price" id="price" placeholder="请填写零售价"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">团购价</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="group_price" id="group_price" placeholder="请填写团购价"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">团购人数</label>
                <div class="col-md-4">
                    <input type="text" class="form-control" name="group_limit" id="group_limit" placeholder="请填写团购人数"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">商品图片</label>
                <div class="col-md-4">
                    <img class="img-thumbnail" id="image-preview" width="300" height="300" src="no_image.php?w=300&h=300"/>
                    <input type="hidden" name="image" id="image"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">缩略图</label>
                <div class="col-md-4">
                    <img class="img-thumbnail" id="thumb-preview" width="120" height="120" src="no_image.php?w=120&h=120"/>
                    <input type="hidden" name="thumb" id="thumb"/>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">商品简介</label>
                <div class="col-md-4">
                    <textarea class="form-control" name="desc" id="desc" placeholder="请填写商品简介"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">商品详情</label>
                <div class="col-md-4">
                    <textarea name="detail" id="detail"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">排序</label>
                <div class="col-md-4">
                    <input type="number" class="form-control" name="sort" id="sort" placeholder="请填写排序" value="50"/>
                    <div class="help-block">请填写正整数，数字越小，排序越前</div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">状态</label>
                <div class="col-md-4">
                    <select class="form-control" name="status" id="status">
                        <option value="0">下架</option>
                        <option value="1">上架</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">&nbsp;</label>
                <div class="col-md-10">
                    <button class="btn btn-primary" name="submit" id="submit">新增</button>
                    <a class="btn btn-default" href="product.php?act=list">返回</a>
                </div>
            </div>
        </form>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>
<link rel="stylesheet" href="../plugins/common/kindeditor/themes/default/default.css" />
<script src="../plugins/common/kindeditor/kindeditor.js"></script>
<script src="../plugins/common/kindeditor/lang/zh_CN.js"></script>
<link rel="stylesheet" href="../plugins/common/kindeditor/plugins/code/prettify.css" />
<script charset="utf-8" src="../plugins/common/kindeditor/plugins/code/prettify.js"></script>

<script type="text/javascript">
    var content = null;

    KindEditor.ready(function(K) {
        var editor = K.editor({
            allowFileManager : true
        });
        K('#image-preview').click(function() {
            editor.loadPlugin('insertimage', function() {
                editor.plugin.imageDialog({
                    imageUrl : K('#image').val(),
                    clickFn : function(url) {
                        K('#image').val(url);
                        K('#image-preview').attr('src', url);
                        editor.hideDialog();
                    }
                });
            });
        });
        K('#thumb-preview').click(function() {
            editor.loadPlugin('insertimage', function() {
                editor.plugin.imageDialog({
                    imageUrl : K('#thumb').val(),
                    clickFn : function(url) {
                        K('#thumb').val(url);
                        K('#thumb-preview').attr('src', url);
                        editor.hideDialog();
                    }
                });
            });
        });
        content = K.create('textarea[name="detail"]', {
            allowFileManager : true,
            width: 670,
            height: 300,
            afterCreate : function() {
                var self = this;
                K.ctrl(document, 13, function() {
                    self.sync();
                    K('form')[0].submit();
                });
                K.ctrl(self.edit.doc, 13, function() {
                    self.sync();
                    K('form')[0].submit();
                });
            }
        });
        prettyPrint();
    });

    function add_product() {
        content.sync();
        var data = {
            name: $.trim($('#name').val()),
            category_id: parseInt($('#category_id').val()),
            unit: $.trim($('#unit').val()),
            market_price: parseFloat($('#market_price').val()),
            price: parseFloat($('#price').val()),
            group_price: parseFloat($('#group_price').val()),
            group_limit: parseInt($('#group_limit').val()),
            image: $.trim($('#image').val()),
            thumb: $.trim($('#thumb').val()),
            desc: $('#desc').val(),
            detail: $('#detail').val(),
            sort: parseInt($('#sort').val()),
            status: parseInt($('#status').val()),
            brand_id: parseInt($('#brand_id').val()),
            opera: 'add'
        };

        var error_msg = '';

        if(data.name == '') {
            error_msg += '-请填写商品标题<br/>';
            $('#name').parent().addClass('has-error');
        } else {
            $('#name').parent().removeClass('has-error');
        }

        if(isNaN(data.category_id) || data.category_id < 0) {
            error_msg += '-请选择商品分类<br/>';
            $('#category_id').parent().addClass('has-error');
        } else {
            $('#category_id').parent().removeClass('has-error');
        }

        if(data.unit == '') {
            error_msg += '-请填写单位<br/>';
            $('#unit').parent().addClass('has-error');
        } else {
            $('#unit').parent().removeClass('has-error');
        }

        if(isNaN(data.market_price) || data.market_price < 0) {
            error_msg += '-请填写市场价<br/>';
            $('#market_price').parent().addClass('has-error');
        } else {
            $('#market_price').parent().removeClass('has-error');
        }

        if(isNaN(data.price) || data.price <= 0) {
            error_msg += '-请填写零售价<br/>';
            $('#price').parent().addClass('has-error');
        } else {
            $('#price').parent().removeClass('has-error');
        }

        if(isNaN(data.group_price) || data.group_price <= 0) {
            error_msg += '-请填写团购价<br/>';
            $('#group_price').parent().addClass('has-error');
        } else {
            $('#group_price').parent().removeClass('has-error');
        }

        if(isNaN(data.group_limit) || data.group_limit <= 0) {
            error_msg += '-请填写团购人数<br/>';
            $('#group_limit').parent().addClass('has-error');
        } else {
            $('#group_limit').parent().removeClass('has-error');
        }

        if(data.image == '') {
            error_msg += '-请选择商品图片<br/>';
            $('#image').parent().addClass('has-error');
        } else {
            $('#image').parent().removeClass('has-error');
        }

        if(data.thumb == '') {
            error_msg += '-请选择缩略图<br/>';
            $('#thumb').parent().addClass('has-error');
        } else {
            $('#thumb').parent().removeClass('has-error');
        }

        if(data.desc == '') {
            error_msg += '-请填写商品简介<br/>';
            $('#desc').parent().addClass('has-error');
        } else {
            $('#desc').parent().removeClass('has-error');
        }

        if(data.detail == '') {
            error_msg += '-请填写商品详情<br/>';
            $('#detail').parent().addClass('has-error');
        } else {
            $('#detail').parent().removeClass('has-error');
        }

        if(isNaN(data.sort) || data.sort < 0) {
            error_msg += '-请填写排序<br/>';
            $('#sort').parent().addClass('has-error');
        } else {
            $('#sort').parent().removeClass('has-error');
        }

        if(error_msg == '') {
            var url = 'product.php';

            $.post(url, data, add_product_success, 'json');
        } else {
            layer.alert(error_msg);
        }

        return false;
    }

    function add_product_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                btn: ['继续添加', '查看列表'],
                yes: function(index, layero) {
                    layer.close(index);
                    window.location.reload();
                },
                cancel: function() {
                    window.location.href = 'product.php?act=list';
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}