{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th>商品标题</th>
                    <th>所属分类</th>
                    <th>所属品牌</th>
                    <th>商品图片</th>
                    <th>市场价</th>
                    <th>零售价</th>
                    <th>添加时间</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
            {if isset($product_list) and count($product_list)}
            {foreach $product_list as $product}
            <tr>
                <td>{$product.name}</td>
                <td>{$product.category_name}</td>
                <td>{$product.brand_name}</td>
                <td><img src="{$product.image}" width="100px"/></td>
                <td>{sprintf('¥%.2f', $product.market_price)}</td>
                <td>{sprintf('¥%.2f', $product.price)}</td>
                <td>{date('Y-m-d H:i:s', $product.add_time)}</td>
                <td>
                    {if $product.status eq 1}
                    <span class="label label-success">上架</span>
                    {else}
                    <span class="label label-default">下架</span>
                    {/if}
                </td>
                <td>
                    <a href="#link-modal" class="btn btn-default link-btn" data-toggle="modal" data-href="http://{$smarty.server.SERVER_NAME}/product.php?id={$product.id}">
                        <i class="glyphicon glyphicon-link"></i>
                    </a>
                    <a href="../product.php?id={$product.id}" class="btn btn-default" title="预览">
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </a>

                    <a href="product.php?act=edit&id={$product.id}" class="btn btn-default" title="编辑">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>

                    <a href="javascript:void(0);" data-id="{$product.id}" class="btn btn-default delete" title="删除">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td colspan="9" class="text-center">
                    暂无商品，请先 <a href="article.php?act=add">添加</a>
                </td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="link-modal">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        $('.delete').bind('click', delete_product);

        $('.link-btn').click(function () {
            $('.modal-title').text('链接');
            $('.modal-body>p').text($(this).attr('data-href'));
        });
    });

    function delete_product() {
        var data = {
            id: $(this).attr('data-id'),
            opera: 'delete'
        };

        var url = 'product.php';

        layer.confirm('您确定要删除该商品?', { icon: 3 }, function() {
            $.post(url, data, delete_product_success, 'json');
        });
    }

    function delete_product_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                yes: function() {
                    window.location.reload();
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}