{extends file='common/template.phtml'}
{block name='content'}
<div class="panel panel-default">
    <div class="panel-heading">
        <span class="panel-title">{$_P['page']['title']}</span>
    </div>
    <div class="panel-body">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th>品牌名称</th>
                    <th>品牌LOGO</th>
                    <th>创建时间</th>
                    <th>修改时间</th>
                    <th>状态</th>
                    <th>链接</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
            {if isset($brand_list) and count($brand_list)}
            {foreach $brand_list as $brand}
            <tr>
                <td>{$brand.name|escape}</td>
                <td><img src="{$brand.logo}" width="100px"/></td>
                <td>{date('Y-m-d H:i:s', $brand.add_time)}</td>
                <td>{$brand.last_modify}</td>
                <td>
                    {if $brand.status eq 1}
                    <span class="label label-success">已发布</span>
                    {else}
                    <span class="label label-default">存草稿</span>
                    {/if}
                </td>
                <td>http://{$smarty.server.SERVER_NAME}/brand.php?id={$brand.id}</td>
                <td>
                    <a href="../brand.php?id={$brand.id}" class="btn btn-default" title="预览">
                        <i class="glyphicon glyphicon-eye-open"></i>
                    </a>

                    <a href="brand.php?act=edit&id={$brand.id}" class="btn btn-default" title="编辑">
                        <i class="glyphicon glyphicon-pencil"></i>
                    </a>

                    <a href="javascript:void(0);" data-id="{$brand.id}" class="btn btn-default delete" title="删除">
                        <i class="glyphicon glyphicon-trash"></i>
                    </a>
                </td>
            </tr>
            {/foreach}
            {else}
            <tr>
                <td colspan="8" class="text-center">
                    暂无品牌，请先 <a href="brand.php?act=add">添加</a>
                </td>
            </tr>
            {/if}
            </tbody>
        </table>
    </div>
    <div class="panel-footer text-right">
        {$_P['page']['copyright']}
    </div>
</div>
<script type="text/javascript">
    $(function(){
        var delete_btns = $('.delete');

        delete_btns.each(function(i, e) {
            $(this).bind('click', delete_brand);
        });
    });

    function delete_brand() {
        var data = {
            id: $(this).attr('data-id'),
            opera: 'delete'
        };

        var url = 'brand.php';

        layer.confirm('您确定要删除该品牌?', { icon: 3 }, function() {
            $.post(url, data, delete_brand_success, 'json');
        });
    }

    function delete_brand_success(response) {
        if(response.error == 0) {
            layer.open({
                shade: [0.5, '#333333'],
                icon: 1,
                closeBtn: 0,
                content: response.message,
                yes: function() {
                    window.location.reload();
                }
            });
        } else {
            layer.alert(response.message);
        }
    }
</script>
{/block}